version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # target: development
    container_name: app
    env_file:
      - .env.development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  
  mongo:
    image: mongo
    container_name: mongo_db
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    ports:
      - '27018:27017' # Exposing to port 27018 is only needed if the host is already running some PID on port 270107, which might be another Mongo instance. This answer may be confusing


volumes:
  node_modules: